steps:
- name: gcr.io/kaniko-project/executor:latest
  args:
      - --destination=gcr.io/$PROJECT_ID/hello-app:$SHORT_SHA
      - --cache=false
      - --cache-ttl=10h
      - --dockerfile=hello-app/Dockerfile
- name: "gcr.io/cloud-builders/gke-deploy"
  args:
  - run
  - --filename=hello-app/manifests/helloweb-deployment.yaml
  - --image=gcr.io/$PROJECT_ID/hello-app:$SHORT_SHA
  - --location=us-central1-c
  - --cluster=cluster-1
substitutions:
  _DIST_BUCKET: abucket # default value
timeout: 10800s
options:
  machineType: 'N1_HIGHCPU_32'